#!/bin/bash

modules=`./show_modules | tee doc/modules.lst`

cd doc
rm index.rst

TOTAL_LINES=`cat _templates/template.rst | wc -l`
BEGIN_LINE=`grep -n -e 'available_modules' _templates/template.rst | cut -d : -f 1`
TAIL_LINES=$(($TOTAL_LINES-$BEGIN_LINE))
BEGIN_LINE=$(($BEGIN_LINE-1))
head -n $BEGIN_LINE _templates/template.rst >> index_tmp.rst
cat modules.lst | sed 's,^,* ,g' >> index_tmp.rst
tail -n $TAIL_LINES _templates/template.rst >> index_tmp.rst

echo '.. toctree::' >> docs.lst
#echo '   :maxdepth: 2' >> docs.lst
for doc in `ls ../nt`; do
	if [ $doc != "__init__.py" ]
	then
		cp ../nt/${doc}/index.rst tmp.rst
		echo "   ${doc}_tmp" >> docs.lst
		if grep -q $doc conf.py
			then
			 echo "${doc} already included"
			else
		     echo "sys.path.append(os.path.abspath('../nt/${doc}'))" >> conf.py
		fi
		sed "s/automodule:: /automodule:: ${doc}./g" tmp.rst > ${doc}_tmp.rst
	fi
done
rm tmp.rst

TOTAL_LINES=`cat index_tmp.rst | wc -l`
BEGIN_LINE=`grep -n -e 'doc_modules' index_tmp.rst | cut -d : -f 1`
TAIL_LINES=$(($TOTAL_LINES-$BEGIN_LINE))
BEGIN_LINE=$(($BEGIN_LINE-1))
head -n $BEGIN_LINE index_tmp.rst >> index.rst
cat docs.lst >> index.rst
tail -n $TAIL_LINES index_tmp.rst >> index.rst

rm index_tmp.rst
rm docs.lst
rm modules.lst

make html

rm *_tmp.rst
cd ..

ln -s doc/_build/html/index.html documentation.html